
services:
    db:
      image: mysql
      container_name: mysql_container
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
          - mySql:/var/lib/mysql
      ports:
          - "3306:3306"
      restart: always

volumes:
  mySql: